networks:
  net_public:
    external: true
    name: public
    
services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    hostname: wiki.domain.local
    container_name: wiki
    networks:
      - public
#    depends_on:
#      - db
#    init: true
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wikijs
    restart: unless-stopped
    ports:
      - "80:3000"
    volumes:
      - ./content:/wiki/data/content
      - ./config.yml:/wiki/config.yml
      - ./bck:/wiki/data/export
